spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: root

  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

# Example for configuring generic S3 store without cloud profile (i.e. Minio)
#s3:
#  access_key_id: {s3 access key}
#  secret_access_key: {s3 access secret}
#  bucket: movie-fun-bucket
#  endpointurl: http://127.0.0.1:9000